#!/bin/bash
# Script to create demonstration GIFs for Django Keel

echo "==================================="
echo "Django Keel - Quick Start Demo"
echo "==================================="
echo ""
echo "This demonstrates creating a SaaS project with one command:"
echo ""
echo "$ copier copy gh:CuriousLearner/django-keel my-saas-project --data-file quick-config.yml --trust"
echo ""
echo "Using pre-configured answers for a SaaS application..."
echo "- Project type: SaaS (Multi-tenant with billing)"
echo "- Python: 3.14"
echo "- Package manager: uv"
echo "- API: Django REST Framework"
echo "- Frontend: Next.js"
echo "- Database: PostgreSQL"
echo "- Cache: Redis"
echo "- Teams: Enabled"
echo "- Stripe: Advanced (dj-stripe)"
echo "- Background: Celery"
echo "- Deployment: Kubernetes"
echo ""
echo "Project generated successfully in ./my-saas-project!"
echo ""
echo "Next steps:"
echo "  cd my-saas-project"
echo "  uv sync"
echo "  docker compose up -d"
echo "  just migrate"
echo "  just dev"
